FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --upgrade pip && \
    pip install dbt-snowflake==1.7.5
ENTRYPOINT ["dbt"]
CMD ["--help"]
