FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY Consumer/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY Scripts/spotify_consumer.py .

CMD ["python", "-u", "spotify_consumer.py"]
