// Measures for spotify.pbix (CSV import uses UPPERCASE column names from Snowflake)
// If your columns are lowercase, change DATE -> date, etc.

Total Plays =
SUM ( gold_daily_summary[TOTAL_PLAY_COUNT] )

Unique Artists =
DISTINCTCOUNT ( gold_daily_summary[ARTIST_NAME] )

Unique Tracks =
DISTINCTCOUNT ( gold_daily_summary[TOP_TRACK] )

Avg Track Length (sec) =
AVERAGE ( gold_daily_summary[AVG_DURATION_SEC] )

Total Listen Events =
COUNTROWS ( silver_tracks )

Top Track Today =
VAR TodayDate = MAX ( gold_daily_summary[DATE] )
VAR MaxPlays =
    CALCULATE (
        MAX ( gold_daily_summary[TOTAL_PLAY_COUNT] ),
        gold_daily_summary[DATE] = TodayDate
    )
RETURN
    CALCULATE (
        MAX ( gold_daily_summary[TOP_TRACK] ),
        gold_daily_summary[DATE] = TodayDate,
        gold_daily_summary[TOTAL_PLAY_COUNT] = MaxPlays
    )

Plays Last 7 Days =
CALCULATE (
    [Total Plays],
    gold_daily_summary[DATE] >= TODAY () - 7
)

Total Listening Time (min) =
SUM ( silver_tracks[DURATION_MS] ) / 60000

Last Refreshed =
MAX ( silver_tracks[INGESTION_TIMESTAMP] )

// --- Storytelling measures (Page 1–3) ---

Top Artist =
VAR TopArtistPlays =
    MAXX (
        SUMMARIZE ( gold_daily_summary, gold_daily_summary[ARTIST_NAME], "Plays", [Total Plays] ),
        [Plays]
    )
RETURN
    CALCULATE (
        MAX ( gold_daily_summary[ARTIST_NAME] ),
        FILTER (
            SUMMARIZE ( gold_daily_summary, gold_daily_summary[ARTIST_NAME], "Plays", [Total Plays] ),
            [Plays] = TopArtistPlays
        )
    )

Top Track =
VAR TopTrackPlays =
    MAXX (
        SUMMARIZE ( gold_daily_summary, gold_daily_summary[TOP_TRACK], "Plays", [Total Plays] ),
        [Plays]
    )
RETURN
    CALCULATE (
        MAX ( gold_daily_summary[TOP_TRACK] ),
        FILTER (
            SUMMARIZE ( gold_daily_summary, gold_daily_summary[TOP_TRACK], "Plays", [Total Plays] ),
            [Plays] = TopTrackPlays
        )
    )

Play Share % =
DIVIDE ( SUM ( gold_daily_summary[TOTAL_PLAY_COUNT] ), [Total Plays], 0 )

Avg Plays Per Day =
DIVIDE ( [Total Plays], DISTINCTCOUNT ( gold_daily_summary[DATE] ), 0 )

Listening Hours =
SUM ( silver_tracks[DURATION_MS] ) / 3600000

Top Track Rank =
RANKX (
    ALLSELECTED ( gold_daily_summary[TOP_TRACK] ),
    CALCULATE ( SUM ( gold_daily_summary[TOTAL_PLAY_COUNT] ) ),
    ,
    DESC,
    Dense
)

Is Top 5 Track =
IF ( [Top Track Rank] <= 5, "Top 5", "Other" )
